### ISSUE TITLE
Can not get data from device-sdk-c example

### ISSUE THREAD

**Issue by Jan5566** [edgexfoundry/device-sdk-c#511]
I use example and build form [here](https://github.com/edgexfoundry/device-sdk-c/blob/main/src/c/examples/template.c)
It seems to be connected, but I can't get the data by calling the API as following. Any idea to deal with this problem, thanks in advance.
![2024-03-07 195208](https://github.com/edgexfoundry/community/assets/61963088/b61c2aa1-a81b-47e0-9ae6-e8c87600df30)

device service log:
```
level=DEBUG ts=2024-03-07T11:43:31Z app=device-template correlation-id=3cc171df-614a-41b5-add3-9294bd7d8875 msg="GET on device:"
level=DEBUG ts=2024-03-07T11:43:31Z app=device-template correlation-id=3cc171df-614a-41b5-add3-9294bd7d8875 msg=" [Other] protocol:"
level=DEBUG ts=2024-03-07T11:43:31Z app=device-template correlation-id=3cc171df-614a-41b5-add3-9294bd7d8875 msg="    Address = someSensorEndpoint"
level=DEBUG ts=2024-03-07T11:43:31Z app=device-template correlation-id=3cc171df-614a-41b5-add3-9294bd7d8875 msg="  Requested reading 0:"
level=DEBUG ts=2024-03-07T11:43:31Z app=device-template correlation-id=3cc171df-614a-41b5-add3-9294bd7d8875 msg="    SensorID = "Sen1""
level=DEBUG ts=2024-03-07T11:43:31Z app=device-template correlation-id=3cc171df-614a-41b5-add3-9294bd7d8875 msg="    SensorType = "UInt64""
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template msg="Publishing metrics"
level=INFO ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg="AutoEvent: Device1/SensorOne"
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg="GET on device:"
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg=" [Other] protocol:"
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg="    Address = someSensorEndpoint"
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg="  Requested reading 0:"
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg="    SensorID = "Sen1""
level=DEBUG ts=2024-03-07T11:43:41Z app=device-template correlation-id=69ebaa1d-7269-4931-956c-5e72cc10c19b msg="    SensorType = "UInt64""
```

edgex-core-data log:
```
level=ERROR ts=2024-03-07T11:43:51.7875861Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:44:01.7879098Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:44:11.7880277Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:44:21.7884887Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:44:31.7885904Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:44:41.7885902Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:44:51.7889038Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:45:01.7891573Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
level=ERROR ts=2024-03-07T11:45:11.7892706Z app=core-data source=subscriber.go:77 msg="fail to unmarshal event, invalid character '\\x00' after top-level value"
```

configuration.yaml:
```
Writable:
  LogLevel: DEBUG
  Driver:
    TestParam2: World
    TestParam3: Goodbye

Service:
  Host: 127.0.0.1
  Port: 59990
  StartupMsg: Template device started

Clients:
  core-metadata:
    Host: "localhost"
    Port: 59881

Driver:
  TestParam1: "Hello"

Device:
  Labels: [ "Template" ]
  ProfilesDir: "./res/profiles"
  DevicesDir: "./res/devices"

MessageBus:
  Protocol: redis
  Host: localhost
  Port: 6379
  Type: redis
  AuthMode: "usernamepassword"  # required for redis messagebus (secure or insecure)
  SecretName: redisdb
  Optional:
    ClientId: device-template
```
profiles/TemplateProfile.json:
```
{
  "name": "TemplateSensor",
  "manufacturer": "IoTechSystems",
  "model": "IoT0",
  "description": "Template Sensor",
  "labels": ["sensor"],
  "apiVersion": "v2",

  "deviceResources":
  [
    {
      "name": "SensorOne",
      "description": "A Sensor generating unsigned integer values",
      "attributes": { "SensorID": "Sen1" , "SensorType": "UInt64" },
      "properties": { "valueType": "Uint64", "readWrite": "R", "units": "things" }
    },
    {
      "name": "SensorTwo",
      "description": "A Sensor generating unsigned integer values",
      "attributes": { "SensorID": "Sen2", "SensorType": "UInt64" },
      "properties": { "valueType": "Uint64", "readWrite": "R", "units": "things" }
    },
    {
      "name": "Switch",
      "description": "A generic switch",
      "attributes": { "SensorID": "Switch1", "SensorType": "Switch" },
      "properties": { "valueType": "Bool", "readWrite": "RW", "units": "State" }
    }
  ]
}
```

devices/device1.json
```
{
  "name": "Device1",
  "profileName": "TemplateSensor",
  "description": "An Example Template Device",
  "protocols":
  {
     "Other": { "Address": "someSensorEndpoint" }
  },
  "autoEvents":
  [
    { "sourceName": "SensorOne", "onChange": false, "interval": "10s" }
  ]
}

```
